### ISSUE TITLE
untuk kelas Mobile Programming Android & kotlin dan Mastering Mobile Programming Android

### ISSUE THREAD

**Issue by kazuiains** [skillacademyid/programming-with-android#1]
dimohon Source Codenya dibuat branches. agar sewaktu-waktu dapat membuka kembali untuk mempelajari ulang. kalo kaya gini kesannya sia-sia beli kelasnya.

**Comment by nick2905** [comment]
Maaf, kenapa source codenya malah hasil daripada convert dari code sebelumnya yah? Tolong dong sourcenya itu full source... Gimana mau belajar codenya kalau gini...
Untuk kelas 500 ribu, sangat kurang menurut saya. Udemy saja lebih dari sini. Terima kasih

**Comment by budioktaviyan** [comment]
Mohon maaf sebelumnya mas, sengaja dibuat seperti ini. Tujuannya agar tidak terlalu banyak branching system pada `git`. Sehingga, dibuatkan dengan cara `checkout per commit history`. Mas nya dapat melakukan hal tersebut dengan mudah menggunakan `git client`

Selain itu, untuk memudahkan dalam membuat branching system sesuai kebutuhan pembelajaran teman"
