### ISSUE TITLE
Kelas Mastering SkillAcademy

### ISSUE THREAD

**Issue by nicolasmanurung** [skillacademyid/programming-with-android#2]
Maaf, kenapa source codenya malah hasil daripada convert dari code sebelumnya yah? Tolong dong sourcenya itu full source... Gimana mau belajar codenya kalau gini...
Untuk kelas 500 ribu, sangat kurang menurut saya. Udemy saja lebih dari sini. Terima kasih

**Comment by budioktaviyan** [comment]
Mohon maaf sebelumnya mas, sengaja dibuat seperti ini. Tujuannya agar tidak terlalu banyak branching system pada `git`. Sehingga, dibuatkan dengan cara `checkout per commit history`. Mas nya dapat melakukan hal tersebut dengan mudah menggunakan `git client`

Selain itu, untuk memudahkan dalam membuat branching system sesuai kebutuhan pembelajaran teman"
